# Generated by Django 4.1.4 on 2022-12-09 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=255)),
                ("open_time", models.CharField(blank=True, max_length=100)),
                ("close_time", models.CharField(blank=True, max_length=100)),
                (
                    "total_available_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "price_per_hour",
                    models.FloatField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(10)],
                    ),
                ),
                (
                    "created_at",
                    models.CharField(
                        default="09 Dec, 2022 - 02h34m30 PM", max_length=100
                    ),
                ),
                (
                    "updated_at",
                    models.CharField(
                        default="09 Dec, 2022 - 02h34m30 PM", max_length=100
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playground_city",
                        to="location_app.cities",
                        to_field="city_name",
                    ),
                ),
                (
                    "playground_owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playground_owner",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
