# Generated by Django 4.1.4 on 2022-12-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location_app", "0002_remove_cities_number_of_playgrounds"),
        ("playground_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="city",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playgrounds",
                to="location_app.cities",
                to_field="city_name",
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="10 Dec, 2022 - 03h04m56 PM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="10 Dec, 2022 - 03h04m56 PM", max_length=100
            ),
        ),
    ]
