# Generated by Django 4.1.4 on 2022-12-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playground_app",
            "0002_alter_playground_city_alter_playground_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="12 Dec, 2022 - 01h29m46 PM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="12 Dec, 2022 - 01h29m46 PM", max_length=100
            ),
        ),
    ]
