# Generated by Django 4.1.4 on 2022-12-19 14:07

from django.db import migrations, models
import django.db.models.deletion
import playground_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("playground_app", "0003_alter_playground_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="19 Dec, 2022 - 04h07m19 PM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="19 Dec, 2022 - 04h07m19 PM", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=playground_app.models.product_image_location,
                    ),
                ),
                (
                    "playground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="playground_app.playground",
                    ),
                ),
            ],
        ),
    ]
