# Generated by Django 4.1.4 on 2022-12-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground_app", "0005_image_thumbnail_alter_playground_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Image", new_name="PlaygroundImage",),
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="20 Dec, 2022 - 01h23m10 PM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="20 Dec, 2022 - 01h23m10 PM", max_length=100
            ),
        ),
    ]
