# Generated by Django 4.1.4 on 2022-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground_app", "0006_rename_image_playgroundimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playground",
            name="created_at",
            field=models.CharField(
                default="20 Dec, 2022 - 01h36m33 PM", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="updated_at",
            field=models.CharField(
                default="20 Dec, 2022 - 01h36m33 PM", max_length=100
            ),
        ),
    ]
